server:
  port: 18889
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 23215d932d21213631212109029fb21230c
            client-secret: 1a920ec7e3657be617b