server:
  port: 18889
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 35d932d29fb30c
            client-secret: 1a920ec7e3657be61734252f9989d590404e