server:
  port: 18889
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 35d932d23609029fb30cd
            client-secret: 1a920ec7e3657be617b1b534252f9989d590404ef