server:
  port: 18889

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 23215d932d21213631212109029fb21230c
            client-secret: 1a92ff0ec7e365as7be617b
            redirect-uri-template: "{baseUrl/register/social/{registraionId}"
          qq:
            client-id: 23215d932d21213631212109029fb21230c
            client-secret: 1a92ff0ec7e365as7be617b
            provider: qq
            client-name: QQ登录
            authorization-grant-type: authorization_code
            client_authentication-method: post
            scope: get_user_info,list_album,upload_pic,do_like
            redirect-uri-template: "{baseUrl/register/social/{registraionId}"
        provider:
          qq:
            #获取code
            authorization-uri: https://graph.qq.com/oauth2.0/authorize
            #获取token
            token-uri: https://graph.qq.com/oauth2.0/token
            #获取openid
            user-info-uri: https//graph.qq.com/oauth2.0/me
            user-name-attribute: "nickname"
