server:
  port: 9090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:9998/me